### ISSUE TITLE
 HP Elitebook 830 G6 - Ventura EFI

### ISSUE THREAD

**Issue by rhcndrsn** [stevedat/HP-Elitebook-830-G6-Hackintosh#23]
Hi,

I have Elitebook830 and im using ventura hackintosh. I research EFI for my laptop and tried many EFI for work. I found different elitebook EFI for boot and its working only graph, sound (only output). I need to fix HDMI output, sound card mic input and webcam. Can you share If you have updated EFI for Ventura and Sonoma?

**Comment by stevedat** [comment]
Sorry mate, am out of this quite long time ago.

**Comment by stevedat** [comment]
I think that you better git a Macbook Air and run it with OLP, much better than Hackintosh on Windows laptops.

**Comment by rhcndrsn** [comment]
yeah you're right but its little expensive in Turkey ;)

**Comment by stevedat** [comment]
> yeah you're right but its little expensive in Turkey ;)

I bought MBA 2015, running Sonoma 14.2. Its price is about USD200 old-used condition, depends on condition the price can be vary.

**Comment by stevedat** [comment]
> yeah you're right but its little expensive in Turkey ;)

Just inbox you, too.

**Comment by stevedat** [comment]
> yeah you're right but its little expensive in Turkey ;)

Text me Whatsapp +84 8654 00 630
Turkey, an interesting country.
