### ISSUE TITLE
Dear steve,can you share your EFI in Big Sur or Catalina?

### ISSUE THREAD

**Issue by cs8878701** [stevedat/HP-Elitebook-830-G6-Hackintosh#3]
For some reasons, I have to use my 830-G6 to install macOS for working. I am so happy that I found your project on github.I have some issues, I hope you can help me.

- (1)For 830-G6, which version is stable? Big Sur or Catalina?
Based on your answer, please give me your EFI, thanks!
- (2)I found that my hardware is different to you and tookdes.
My memory is 16 GB Hynix/Hyundai 2666MHz DDR4 one slot and my SSD is koxia XG6 , is that ok to use your EFI?
My WiFi is Intel AX200, can i just use your EFI?Because I see you used airportitlwm.
- (3)To be honest, i am a fun for hackintosh. But i am a freshman, could I just use your EFI to run macOS or I have to config something in EFI?Like serial number?
- Thanks for answering.

**Comment by stevedat** [comment]
Thanks for reaching out to me, and your active in search of me available on Reddit :))
Shared.

**Comment by stevedat** [comment]
Provided EFI

**Comment by stevedat** [comment]
I got it work. Pinged u a chat
