### ISSUE TITLE
please share EFI here

### ISSUE THREAD

**Issue by VGerris** [stevedat/HP-Elitebook-830-G6-Hackintosh#7]
hi,

please share the EFI and describe what you did to create it?
don't forget to set serial to 000 or something.

thanks

**Comment by stevedat** [comment]
@VGerris shared, Github error not loaded the file.

**Comment by VGerris** [comment]
Thanks for sharing. Doesn't boot the Big Sur installer for me unfortunately. You mentioned pre and post install, any differences? Process description would be great too :).
Gonna try and make it work, thank you again!

**Comment by stevedat** [comment]
> Thanks for sharing. Doesn't boot the Big Sur installer for me unfortunately. You mentioned pre and post install, any differences? Process description would be great too :).
> Gonna try and make it work, thank you again!

Which error you got? If is bios settings too and make own change to fit to your hardware.
Post-installation is about Kexts and some personal tweaks.

**Comment by VGerris** [comment]
Hi,

It hangs on boot. I got some things working now by combining your EFI with
the Catalina one on github ( seems yours is using same dsdt). Not sure on
precise problem yet.
So far I do not have proper sleep and the webcam does not work. HDMI port
not either.
I'm still experimenting, probably will upload when it works. Got wifi on
AX200, no bluetooth.
The rest seems to work so far.
Ideas are welcome and perhaps your running EFI? Thanks a lot anyway, your
stuff helped me making sound work.
Running Montery 12.1 now and OpenCore 0.7.7.

Cheers

**Comment by stevedat** [comment]
> Hi, It hangs on boot. I got some things working now by combining your EFI with the Catalina one on github ( seems yours is using same dsdt). Not sure on precise problem yet. So far I do not have proper sleep and the webcam does not work. HDMI port not either. I'm still experimenting, probably will upload when it works. Got wifi on AX200, no bluetooth. The rest seems to work so far. Ideas are welcome and perhaps your running EFI? Thanks a lot anyway, your stuff helped me making sound work. Running Montery 12.1 now and OpenCore 0.7.7. Cheers
> […](#)

Post EFI - https://drive.google.com/file/d/1PQMc-m0R72ikXJCheNfhMyJO36yUL0WF/view?usp=sharing
@VGerris  you can try mine.

**Comment by stevedat** [comment]
> > Hi, It hangs on boot. I got some things working now by combining your EFI with the Catalina one on github ( seems yours is using same dsdt). Not sure on precise problem yet. So far I do not have proper sleep and the webcam does not work. HDMI port not either. I'm still experimenting, probably will upload when it works. Got wifi on AX200, no bluetooth. The rest seems to work so far. Ideas are welcome and perhaps your running EFI? Thanks a lot anyway, your stuff helped me making sound work. Running Montery 12.1 now and OpenCore 0.7.7. Cheers
> > […](#)
> 
> Post EFI - https://drive.google.com/file/d/1PQMc-m0R72ikXJCheNfhMyJO36yUL0WF/view?usp=sharing @VGerris you can try mine.

https://mega.nz/file/1FcnCa5S#DVWYx0Nuf5QR5MijMmHJIU0_E0j18v4VBkKELZwQy0s
